next xkcd check scheduled for: 52905419
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 20)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 21)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 22)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 23)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 24)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 25)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 26)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 27)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 28)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 29)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
Connected as EyanSays (Skarm). Yippee!
(node:11428) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 31)
Dragonite was mentioned, but in a channel they can't view
KugallyBlitz was mentioned, but in a channel they can't view
(node:11428) UnhandledPromiseRejectionWarning: Error: Internal Server Error
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at IncomingMessage.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 32)
FLUBS was mentioned, but in a channel they can't view
next xkcd check scheduled for: 52905419
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 33)
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
next xkcd check scheduled for: 52905419
next xkcd check scheduled for: 52905419
Connected as EyanSays (Skarm). Yippee!
Connected as EyanSays (Skarm). Yippee!
next xkcd check scheduled for: 52905419
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 34)
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 35)
SuperGummying was mentioned, but in a channel they can't view
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
Connected as EyanSays (Skarm). Yippee!
(node:11428) UnhandledPromiseRejectionWarning: Error: connect ETIMEDOUT 104.16.59.5:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 38)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 39)
(node:11428) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND discordapp.com discordapp.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 40)
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Master9000 was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Connected as EyanSays (Skarm). Yippee!
next xkcd check scheduled for: 52905419
Connected as EyanSays (Skarm). Yippee!
Connected as EyanSays (Skarm). Yippee!
Dragonite was mentioned, but in a channel they can't view
Master9000 was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
KugallyBlitz was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Neon Strike Kitty was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 41)
Dragonite was mentioned, but in a channel they can't view
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 42)
(node:11428) UnhandledPromiseRejectionWarning: Error: Forbidden (Missing Permissions)
    at Request.callback (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:698:17)
    at Stream.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\index.js:922:12)
    at Stream.emit (events.js:194:15)
    at Unzip.<anonymous> (C:\bots\SkarmBot\node_modules\superagent\lib\node\utils.js:108:12)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:11428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 43)
next xkcd check scheduled for: 52905419
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Master9000 was mentioned, but in a channel they can't view
139579058152275968 can't view the channel they were mentioned in for whatever reason
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Neon Strike Kitty was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
FLUBS was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
SuperGummying was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
Dragonite was mentioned, but in a channel they can't view
^C